version: '3'
services:
  neo4j:
    image: neo4j:4.2.5
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_max__size: 256M
      NEO4J_dbms_logs_debug_level: DEBUG
